services:
  pagination_app_db:
    image: postgres:${POSTGRES_VERSION}
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PSW}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    command: -p ${POSTGRES_PORT}
    container_name: ${POSTGRES_CONTAINER_NAME}
    expose:
      - "${POSTGRES_PORT}"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pagination_app_db-data:/var/lib/postgresql/data
    networks:
      - pagination-app

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8081
    depends_on:
      pagination_app_db:
        condition: service_healthy
    networks:
      - pagination-app

  app:
    build:
      context: .
      dockerfile: docker_builds/app/Dockerfile
    depends_on:
      pagination_app_db:
        condition: service_healthy
    container_name: "app"
    env_file:
      - .env
    restart: always
    networks:
      - pagination-app
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    command: /usr/local/bin/pagination-app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./observability/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--web.enable-remote-write-receiver"
    ports:
      - "${PROMETHEUS_PORT}:${PROMETHEUS_PORT}"
    depends_on:
      node_exporter:
        condition: service_started
      cadvisor:
        condition: service_started
      postgres_exporter:
        condition: service_started
    networks:
      - pagination-app

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./observability/dashboards/grafana:/var/lib/grafana/dashboards
      - ./observability/provisioning/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./observability/datasources/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    depends_on:
      prometheus:
        condition: service_started
    networks:
      - pagination-app

  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - "--collector.disable-defaults"
      - "--collector.cpu"
      - "--collector.meminfo"
      - "--collector.diskstats"
      - "--collector.netdev"
      - "--collector.filesystem"
    ports:
      - "9100:9100"
    restart: unless-stopped
    networks:
      - pagination-app

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    privileged: true
    restart: unless-stopped
    networks:
      - pagination-app

  postgres_exporter:
    image: prometheuscommunity/postgres-exporter:v0.17.1
    container_name: ${POSTGRES_EXPORTER_CONTAINER_NAME}
    depends_on:
      pagination_app_db:
        condition: service_healthy
    environment:
      DATA_SOURCE_NAME: "postgresql://${POSTGRES_USER}:${POSTGRES_PSW}@${POSTGRES_CONTAINER_NAME}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
      PG_EXPORTER_DISABLE_DEFAULT_METRICS: "true"
    ports:
      - "9187:9187"
    restart: unless-stopped
    networks:
      - pagination-app

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: ${JAEGER_HOST}
    env_file: .env
    ports:
      - "16686:16686" # Jaeger UI
      - "${OTLP_HTTP_PORT}:${OTLP_HTTP_PORT}" # OTLP HTTP endpoint
    networks:
      - pagination-app

  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    env_file:
      - .env
    ports:
      - "8086:8086"
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_TOKEN}
    networks:
      - pagination-app

  k6:
    build:
      context: .
      dockerfile: docker_builds/xk6/Dockerfile
    container_name: k6
    env_file:
      - .env
    volumes:
      - ./scripts/perf_tests:/home/k6
    environment:
      - K6_OUT=xk6-influxdb=http://influxdb:8086
      - K6_INFLUXDB_ORGANIZATION=${INFLUXDB_INIT_ORG}
      - K6_INFLUXDB_BUCKET=${INFLUXDB_INIT_BUCKET}
      - K6_INFLUXDB_INSECURE=true
        # NOTE: This is an Admin token, it's not suggested to use this configuration in production.
        # Instead, use a Token with restricted privileges.
      - K6_INFLUXDB_TOKEN=${INFLUXDB_TOKEN}
      - K6_INFLUXDB_PUSH_INTERVAL=3s # Increase from default 1s
    ports:
      - "6565:6565"
    depends_on:
      influxdb:
        condition: service_started
      app:
        condition: service_healthy
    networks:
      - pagination-app

volumes:
  pagination_app_db-data:
  grafana-storage:
  influxdb-storage:

networks:
  pagination-app:
    driver: bridge
