{
 "title": "Go Runtime",
 "description": "Go Runtime Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Allocated memory",
   "type": "timeseries",
   "description": "Allocated memory Metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "go_memstats_alloc_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "System memory",
   "type": "timeseries",
   "description": "System memory",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "go_memstats_sys_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Goroutine count",
   "type": "timeseries",
   "description": "Goroutine count gouge metric",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "go_goroutines", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  }
 ]
}