# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
          path: |
            ~/.cache/go-build
            /go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('app/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

    - name: Set env file
      working-directory: app
      run: |
        echo "PROJECT_VERSION=${{ vars.PROJECT_VERSION }} >> .env"
        echo "SERVER_PORT=${{ vars.SERVER_PORT }} >> .env"
        echo "POSTGRES_CONTAINER_NAME=${{ secrets.POSTGRES_CONTAINER_NAME }} >> .env"
        echo "POSTGRES_PSW=${{ secrets.POSTGRES_PSW }} >> .env"
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env"
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }} >> .env"
        echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env"
        echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }} >> .env"
        echo "POSTGRES_VERSION=${{ secrets.POSTGRES_VERSION }} >> .env"

    - name: Debug .env
      working-directory: app
      run: cat .env
